// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvlD01hQ1o86_92YQzKmPYWsTePz0pPc',
    appId: '1:290187046863:web:1a3397f87062aefddaacba',
    messagingSenderId: '290187046863',
    projectId: 'maintenex-99b32',
    authDomain: 'maintenex-99b32.firebaseapp.com',
    storageBucket: 'maintenex-99b32.appspot.com',
    measurementId: 'G-2QCPFZEFN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01JPj3ALzbBCJ6mrqa40OepzWgo6h87A',
    appId: '1:290187046863:android:72d9494817567395daacba',
    messagingSenderId: '290187046863',
    projectId: 'maintenex-99b32',
    storageBucket: 'maintenex-99b32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKTg0dx9FW0M27Syr1lg_69B6JObina4',
    appId: '1:290187046863:ios:da12a8c84544ac5cdaacba',
    messagingSenderId: '290187046863',
    projectId: 'maintenex-99b32',
    storageBucket: 'maintenex-99b32.appspot.com',
    androidClientId: '290187046863-e6qf3dkifnuqpspaok89ndovpiddh5vs.apps.googleusercontent.com',
    iosClientId: '290187046863-g0bmv4p708m7lnhe5g993v4n3a3q0edm.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintenex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKTg0dx9FW0M27Syr1lg_69B6JObina4',
    appId: '1:290187046863:ios:d47c77bb13e6212ddaacba',
    messagingSenderId: '290187046863',
    projectId: 'maintenex-99b32',
    storageBucket: 'maintenex-99b32.appspot.com',
    androidClientId: '290187046863-e6qf3dkifnuqpspaok89ndovpiddh5vs.apps.googleusercontent.com',
    iosClientId: '290187046863-e802bo9sdmmhva1kgctfnfdpo84s0g83.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintenex.RunnerTests',
  );
}
